FROM postgres:12.6

USER postgres:postgres
RUN chown postgres:postgres /var/lib/postgresql
RUN chown postgres:postgres /var/lib/postgresql/data
RUN chmod 777 /var/lib/postgresql/data
EXPOSE 5432
CMD ["postgres"]
