FROM postgres:12.6

#USER postgres:postgres
#RUN chown -R postgres:postgres /var/lib/postgresql/data
#RUN chmod 777 /var/lib/postgresql/data
USER 1000650000:1000650000
RUN chown -R 1000650000:1000650000 /var/lib/postgresql/data
RUN chmod 777 /var/lib/postgresql/data
EXPOSE 5432
CMD ["postgres"]
