kind: Deployment
apiVersion: apps/v1
metadata:
  name: potential-app-1
  labels:
    app: potential-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: potential-app-1
  template:
    metadata:
      labels:
        app: potential-app-1
    spec:
      containers:
        - name: potential-app-1
          image: >-
            image-registry.openshift-image-registry.svc:5000/test-sample-1/potential-app-1@sha256:42995dd56726ab130ca48484685539579f6b8acd5233fdc0607bd12515b01c4a
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
